GET http://35.231.254.47:8080/api/v1/book/isbn?isbn=9781133608424
Authorization: password

###

GET http://35.231.254.47:8080/api/v1/feed
Authorization: password

###
GET http://35.231.254.47:8080/api/v1/genre
Authorization: password

###
GET http://35.231.254.47:8080/api/v1/feed/isbn/9780495913504?start=0&limit=5
Authorization: password

### genre list
GET http://localhost:8080/api/v1/genre
Authorization: password

### create book from Books API
GET http://localhost:8080/api/v1/book/isbn?isbn=9781133608424
Authorization: password

### feed from local server
GET http://localhost:8080/api/v1/feed
Authorization: password

### feed from local server of a genre
GET http://localhost:8080/api/v1/feed/genre?genre=Education&start=3&limit=3
Authorization: password

###
GET http://localhost:8080/api/v1/feed/isbn/9780521533850
Authorization: password

### search
GET http://35.231.254.47:8080/api/v1/search?query=college&start=0&limit=5
Authorization: password