GET http://localhost:8080/api/v1/book/5d0a1acaa9134128a54140ab
Authorization: password

### test add request
POST http://localhost:8080/api/v1/request
Authorization: password
Content-Type: application/json

{
    "listing": "5d0a1acaa9134128a54140ab",
    "start": "2019-06-22",
    "end": "2019-07-24"
}

### test reject request
POST http://localhost:8080/api/v1/request/reject
Authorization: password
Content-Type: application/json

{
    "id": "5d11c14ba84e886b767f36e2",
    "reason": "I don't like sharing things"
}

### test accept request
POST http://localhost:8080/api/v1/request/accept
Authorization: password
Content-Type: application/json

{
    "id": "5d11c8eab90d317b2f575967",
    "details": {
        "address": "221B Baker Street, London",
        "mobile": "9090909090",
        "pickup": "2019-06-22T20:20:39+05:30"
    }
}

### test confirm request
POST http://localhost:8080/api/v1/request/confirm
Authorization: password
Content-Type: application/json

{
    "id": "5d11c8eab90d317b2f575967",
    "details": {
        "address": "221B Baker Street, New Delhi",
        "mobile": "9191919191",
        "delivery": "2019-06-23T20:20:39+05:30"
    }
}

### rent notification
GET http://localhost:8080/api/v1/notification/rent
Authorization: password

### lent notification
GET http://localhost:8080/api/v1/notification/lent
Authorization: password

### notification info
GET http://localhost:8080/api/v1/notification/info
Authorization: password

### activity - rent
GET http://localhost:8080/api/v1/activity/rent
Authorization: password

### activity - lent
GET http://localhost:8080/api/v1/activity/lent
Authorization: password

### profile
GET http://localhost:8080/api/v1/profile
Authorization: password

### finish profile
POST http://localhost:8080/api/v1/profile
Authorization: password
Content-Type: application/json

{
    "name": "Saurabh Mittal",
    "mobile": "9090909090"
}

### admin
GET http://localhost:8080/api/v1/admin/rents
Authorization: gf#0BP36u0l3fdMU2.JIdM94xwpbdwzU4ZQe6a3AN

### check
POST http://localhost:8080/api/v1/admin/status
Authorization: gf#0BP36u0l3fdMU2.JIdM94xwpbdwzU4ZQe6a3AN
Content-Type: application/json

{
    "id": "5d11c934dcfb9d7ba8aa2fb3",
    "status": "Confirmed"
}

### get UID
GET http://localhost:8080/api/v1/admin/mobile/9090909090
Authorization: gf#0BP36u0l3fdMU2.JIdM94xwpbdwzU4ZQe6a3AN